[package]
name = "color_palette_dither"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
image = "0.25.9"
image-rs = "0.1.1"
itertools = "0.14.0"
rayon = "1.11.0"
